version: "3"

includes:
  api:
    taskfile: ./apps/api/Taskfile.yaml
    dir: ./apps/api
  web:
    taskfile: ./apps/web/Taskfile.yaml
    dir: ./apps/web

output: prefixed

tasks:
  default:
    cmd: "task --list-all"

  dev:
    desc: "Starts Frontend and Backend server"
    deps: [api:dev, web:dev]
